version: 2
jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build latest
          command: docker build -t wahyd4/aria2-ui:$CIRCLE_BUILD_NUM caddy/.
      - run:
          name: Push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push wahyd4/aria2-ui:$CIRCLE_BUILD_NUM
