name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env: # Or as an environment variable
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }}
      run: docker --version && docker build -t wahyd4/aria2-ui:3.0.$(date +%s) .
    - name: Push Docker image $(github.event_name)==$(github.ref)
      if: github.event_name == 'push' && github.ref == 'master'
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker tag wahyd4/aria2-ui:3.0.$TRAVIS_BUILD_NUMBER wahyd4/aria2-ui:latest
        docker push wahyd4/aria2-ui:3.0.$TRAVIS_BUILD_NUMBER
        docker push wahyd4/aria2-ui:latest
